Update link to a previous header
chaoss/MARS pull request #15
Opened 2021-07-20 16:49 UTC by nicorikken

Apparently the docker header has changed, but the link hasn't.

2021-07-20 17:03 UTC, yash2002109 commented
Thanks @nicorikken,

As a general rule, we require all commits to be signed off with a DCO. You can find more details here: https://github.com/chaoss/governance/blob/master/CONTRIBUTING.md#code-or-document-change-contributions-pull-request

Alternatively, you could also just add a comment in the following format:

Signed-off-by: Your Name YourName@example.org

2021-07-20 18:02 UTC, ritik-malik requested changes

2021-07-20 18:02 UTC, ritik-malik commented on automation-english/README.md
>  #### Step 5: Configuring the yml config file
Thanks for catching the broken link @nicorikken,
I suggest that we also update this heading to match the other one.
i.e. from `Step 5: Configuring the yml config file` to `Step 5: Configuring the yml & Updating the cover page`

2021-07-21 06:44 UTC, nicorikken commented
Thanks @yash2002109 I do these kinds of edits via the online editor, but I think I'd have to add the line myself. I think I should improve on my DCO setup. I fixed it in the mean time.

2021-07-21 06:52 UTC, ritik-malik approved these changes

2021-07-21 06:53 UTC, yash2002109 commented
Thanks @nicorikken for fixing this, LGTM

There is also a web browser plugin that automatically adds the signoff. You may find it useful: <https://github.com/chaoss/governance/blob/master/CONTRIBUTING.md#steps-to-use-the-dco-browser-plugin>

2021-07-21 06:53 UTC, merged

2021-07-26 16:59 UTC, nicorikken commented
@yash2002109 thanks, I'll try it out.